language: ruby
rvm:
  - 3.0.1
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:create db:migrate --trace
  - bundle exec rspec test/
before_script:
  - cp .travis.yml config/database.yml
  - mysql -e 'create database mydb_test'
bundler_args: --binstubs=./bundler_stubs